version: '3.4'

services:
  gamestore.cleanarch.backend.webapi:
    image: ${DOCKER_REGISTRY-}gamestorecleanarchbackendwebapi
    container_name: gamestore.cleanarch.backend.webapi
    build:
      context: .
      dockerfile: GameStore.CleanArch.Backend.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"

  postgresdatabase:
    image: postgres:latest
    container_name: postgresdatabase
    environment:
      - POSTGRES_DB=GameStore
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/gamestore-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
